<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_CONVEYANCE" Id="{7bebbc7a-8549-4ab0-9f56-d4d12bd0462a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_CONVEYANCE
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_CONVEYANCE">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>