<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_TILT_TEST" Id="{fb59190b-17af-4192-a83b-6e0804f23142}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TILT_TEST
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_TILT_TEST">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>